services:
  discord-bot-app:
    image: marcus1939/discord-bot-image
    volumes:
      - ./games_info.json:/app/games_info.json
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
  egs-scraper-app:
    image: marcus1939/egs-scraper-image
    volumes:
      - ./games_info.json:/app/games_info.json